# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-18 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_troubleshooting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrphanCkanObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_name', models.CharField(choices=[('dataset', 'Jeu de données'), ('resource', 'Ressource')], db_column='mimetype', max_length=200, null=True, verbose_name='Objet')),
                ('object_id', models.UUIDField(unique=True, verbose_name="Identifiant de l'object")),
                ('object_location', models.URLField(max_length=2000, verbose_name="URL de l'objet")),
            ],
            options={
                'verbose_name': 'Objet CKAN orphelin',
                'verbose_name_plural': 'Objets CKAN orphelins',
                'db_table': 'idgo_troubleshooting_orphanckanobject',
                'abstract': False,
            },
        ),
    ]
