# Generated by Django 2.2.20 on 2021-04-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeadLinkResource',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(
                    max_length=200, verbose_name='Ressource')),
                ('resource_ckanurl', models.URLField(
                    default='', verbose_name='Lien CKAN')),
                ('external_link', models.CharField(default='',
                 max_length=200, verbose_name='URL erronée')),
                ('package_name', models.CharField(
                    max_length=200, verbose_name='Dataset')),
                ('organization', models.CharField(
                    max_length=200, verbose_name='Organisation')),
                ('last_log', models.DateTimeField(verbose_name='Date du contrôle')),
            ],
            options={
                'verbose_name': 'Liens non valides',
                'verbose_name_plural': 'Liens non valides',
            },
        ),
        migrations.CreateModel(
            name='OutdatedResource',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(
                    max_length=200, verbose_name='Ressource')),
                ('resource_ckanurl', models.URLField(
                    default='', verbose_name='Lien CKAN')),
                ('package_name', models.CharField(
                    max_length=200, verbose_name='Dataset')),
                ('organization', models.CharField(
                    max_length=200, verbose_name='Organisation')),
                ('lastupdate', models.DateTimeField(
                    verbose_name='Dernière mise à jour')),
                ('resource_frequency', models.CharField(blank=True,
                 max_length=100, null=True, verbose_name='Fréquence déclarée')),
                ('delay', models.IntegerField(verbose_name='Retard (en jours)')),
                ('last_log', models.DateTimeField(verbose_name='Date du contrôle')),
            ],
            options={
                'verbose_name': 'Ressource dont la date de MAJ est dépassée',
                'verbose_name_plural': 'Ressources dont la date de MAJ est dépassée',
            },
        ),
        migrations.CreateModel(
            name='UndocumentedPackage',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(
                    max_length=200, verbose_name='Dataset')),
                ('package_ckanurl', models.URLField(
                    default='', verbose_name='Lien CKAN')),
                ('organization', models.CharField(
                    max_length=200, verbose_name='Organisation')),
                ('last_log', models.DateTimeField(verbose_name='Date du contrôle')),
            ],
            options={
                'verbose_name': 'Sans ressource',
                'verbose_name_plural': 'Sans ressource',
            },
        ),
    ]
